.PHONY: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 ex19 ex20 clean

clean :
	rm -r .build
	mkdir .build

ex1 : .build/ex1
	.build/ex1

ex2 : .build/ex2
	.build/ex2

ex3 : .build/ex3
	.build/ex3

ex4 : .build/ex4
	.build/ex4

ex5 : .build/ex5
	.build/ex5

ex6 : .build/ex6
	.build/ex6

ex7 : .build/ex7
	.build/ex7

ex8 : .build/ex8
	.build/ex8

ex9 : .build/ex9
	.build/ex9

ex10 : .build/ex10
	.build/ex10

ex11 : .build/ex11
	.build/ex11

ex12 : .build/ex12
	.build/ex12

ex13 : .build/ex13
	.build/ex13

ex14 : .build/ex14
	.build/ex14

ex15 : .build/ex15
	.build/ex15

ex16 : .build/ex16
	.build/ex16

ex17 : .build/ex17
	.build/ex17

ex18 : .build/ex18
	.build/ex18

ex19 : .build/ex19
	.build/ex19

ex20 : .build/ex20
	.build/ex20

.build/ex1 : src/example1_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex1 src/example1_gr12_HeilikHeorhi.c

.build/ex2 : src/example2_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex2 src/example2_gr12_HeilikHeorhi.c

.build/ex3 : src/example3_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex3 src/example3_gr12_HeilikHeorhi.c

.build/ex4 : src/example4_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex4 src/example4_gr12_HeilikHeorhi.c

.build/ex5 : src/example5_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex5 src/example5_gr12_HeilikHeorhi.c

.build/ex6 : src/example6_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex6 src/example6_gr12_HeilikHeorhi.c

.build/ex7 : src/example7_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex7 src/example7_gr12_HeilikHeorhi.c

.build/ex8 : src/example8_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex8 src/example8_gr12_HeilikHeorhi.c

.build/ex9 : src/example9_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex9 src/example9_gr12_HeilikHeorhi.c

.build/ex10 : src/example10_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex10 src/example10_gr12_HeilikHeorhi.c

.build/ex11 : src/example11_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex11 src/example11_gr12_HeilikHeorhi.c

.build/ex12 : src/example12_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex12 src/example12_gr12_HeilikHeorhi.c

.build/ex13 : src/example13_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex13 src/example13_gr12_HeilikHeorhi.c

.build/ex14 : src/example14_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex14 src/example14_gr12_HeilikHeorhi.c

.build/ex15 : src/example15_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex15 src/example15_gr12_HeilikHeorhi.c

.build/ex16 : src/example16_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex16 src/example16_gr12_HeilikHeorhi.c

.build/ex17 : src/example17_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex17 src/example17_gr12_HeilikHeorhi.c

.build/ex18 : src/example18_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex18 src/example18_gr12_HeilikHeorhi.c

.build/ex19 : src/example19_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex19 src/example19_gr12_HeilikHeorhi.c

.build/ex20 : src/example20_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex20 src/example20_gr12_HeilikHeorhi.c
