.PHONY: ex1

ex1 : .build/ex1
	.build/ex1

ex2 : .build/ex2
	.build/ex2

ex3 : .build/ex3
	.build/ex3

ex4 : .build/ex4
	.build/ex4

ex5 : .build/ex5
	.build/ex5

ex6 : .build/ex6
	.build/ex6

.build/ex1 : src/example1_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex1 src/example1_gr12_HeilikHeorhi.c

.build/ex2 : src/example2_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex2 src/example2_gr12_HeilikHeorhi.c

.build/ex3 : src/example3_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex3 src/example3_gr12_HeilikHeorhi.c

.build/ex4 : src/example4_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex4 src/example4_gr12_HeilikHeorhi.c

.build/ex5 : src/example5_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex5 src/example5_gr12_HeilikHeorhi.c

.build/ex6 : src/example6_gr12_HeilikHeorhi.c
	clang -lsqlite3 -o .build/ex6 src/example6_gr12_HeilikHeorhi.c
